export enum AclRowField {
  FID = "FID_ACL_ROW_FIELD",
  PA = "PA_ACL_ROW_FIELD",
  TYPE = "TYPE_ACL_ROW_FIELD",
  ALT = "ALT_ACL_ROW_FIELD",
  CODE = "CODE_ACL_ROW_FIELD",
  HDG = "HDG_ACL_ROW_FIELD",
  SPD = "SPD_ACL_ROW_FIELD",
  HOLD = "HOLD_ACL_ROW_FIELD",
  ROUTE = "ROUTE_ACL_ROW_FIELD"
}
