export type AclRowField =
  | "FID_ACL_ROW_FIELD"
  | "PA_ACL_ROW_FIELD"
  | "TYPE_ACL_ROW_FIELD"
  | "ALT_ACL_ROW_FIELD"
  | "CODE_ACL_ROW_FIELD"
  | "HDG_ACL_ROW_FIELD"
  | "SPD_ACL_ROW_FIELD"
  | "HOLD_ACL_ROW_FIELD"
  | "ROUTE_ACL_ROW_FIELD";
