export type AclSortOption =
  | "ACL_ACID_SORT_OPTION"
  | "ACL_BOUNDARY_TIME_SORT_OPTION"
  | "ACL_CONFLICT_STATUS_SORT_OPTION"
  | "ACL_CONFLICT_TIME_SORT_OPTION"
  | "ACL_DESTINATION_SORT_OPTION"
  | "ACL_SECTOR_BY_SECTOR_SORT_OPTION";

export const AclSortOptionValues = {
  ACL_ACID_SORT_OPTION: "ACID",
  ACL_BOUNDARY_TIME_SORT_OPTION: "Boundary Time",
  ACL_CONFLICT_STATUS_SORT_OPTION: "Conflict Status",
  ACL_CONFLICT_TIME_SORT_OPTION: "Conflict Time",
  ACL_DESTINATION_SORT_OPTION: "Destination",
  ACL_SECTOR_BY_SECTOR_SORT_OPTION: "Sector-by-Sector",
} as const;
